sudo: false

language: erlang

otp_release:
   - 18.3
   - 18.2.1
   - 18.0
   - 17.5
   - 17.0
   - R16B03-1
   - R16B01

before_install:
   - wget https://s3.amazonaws.com/rebar3/rebar3
   - chmod +x ./rebar3
   - ./rebar3 update
script: "./rebar3 eunit"
